
// AUTH
export const CONNECTED = "CONNECTED"
export const LOGOUT = "LOGOUT"

// CART
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

// NOTIFICATION
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS"
export const REMOVE_NOTIFICATION_ITEM = "REMOVE_NOTIFICATION_ITEM"
